[build]
  command = "python3 -m pip install -r requirements.txt && python3 build.py"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200